### ISSUE TITLE
Enable ci-argocd secret provisioning by eso

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#134]
```
{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.manageEDPInstallSecrets -}}
{{- $secretStore := include "edp-install.secretStoreName" . }}
{{- $awsSecretName := .Values.externalSecrets.manageEDPInstallSecretsName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ci-argocd
spec:
  target:
    template:
      metadata:
        labels:
          app.edp.epam.com/secret-type: argocd
          app.edp.epam.com/integration-secret: "true"
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $secretStore }}
  data:
  - secretKey: token
    remoteRef:
      key: {{ $awsSecretName }}
      property: ci-argocd.token
  - secretKey: url
    remoteRef:
      key: {{ $awsSecretName }}
      property: ci-argocd.url
{{- end }}
```

Acceptance Criteria:

- edp user can onboard 'ci-argocd' secret by ESO;
