### ISSUE TITLE
Add option to parametrize the ssoRealmName value

### ISSUE THREAD

**Issue by Artem-Zahumonnyi** [epam/edp-install#149]
```yaml
# SSO (OAuth2-proxy) configuration section
# The section configures the OAuth2-proxy for single Sign-On (SSO) protection of application endpoints.
#
# More details on setup and deployment:
# - https://epam.github.io/edp-install/operator-guide/oauth2-proxy/
#
# OAuth2-proxy requires Keycloak and Keycloak-operator are properly configured before deployment.
# Ref:
# - https://epam.github.io/edp-install/operator-guide/install-keycloak/
# - https://github.com/epam/edp-cluster-add-ons
# - https://github.com/epam/edp-keycloak-operator
sso:
  # -- Install OAuth2-proxy and Keycloak CRs as a part of EDP deployment.
  enabled: true
  # -- Keycloak URL.
  keycloakUrl: https://keycloak.example.com
  # -- Defines Keycloak realm name that is used as the Identity Provider (IdP) realm
  realmName: "openshift"
```
