### ISSUE TITLE
no ingress found for the GitServer

### ISSUE THREAD

**Issue by hugoarroyo** [epam/edp-install#185]
**Describe the bug**
no ingress found for the GitServer 

**To Reproduce**

#### What did you do?
1. Install EDP version 3.81

2.  I'm able to configure github server configuration following the documentation https://epam.github.io/edp-install/quick-start/integrate-github/

3. creating the Web Applications with Gin Framework

#### What did you expect to see?

The status of the component to be green 

#### What did you see instead? Under which circumstances?
The status of the component is Status failed. The reason is **no ingress found for the Git Server**

**Kubernetes cluster type:**

AWS EKS 1.29

**Comment by SergK** [comment]
Hello @hugoarroyo 

Thank you for contacting us with the details of the issue you're facing with the EPAM Delivery Platform (EDP) version 3.8.1 and the integration of a Git server on an AWS EKS 1.29 Kubernetes cluster.

Based on the information you've provided, it seems the issue revolves around the absence of an ingress for the GitServer, which is leading to the component's status being marked as "failed" due to "no ingress found for the Git Server."

Ingress is indeed a mandatory part of onboarding components within the EDP architecture, especially because it is utilized by WebHooks. The codebase-operator within EDP attempts to retrieve the ingress to set the proper URL for the webhook. That said, there's an **alternative approach** that you might find useful. This approach involves explicitly defining the URL for webhooks, bypassing the operator's need to search for an ingress object.

You can specify the webhook URL in the values.yaml as shown in the following snippet from the [EDP Tekton documentation](https://github.com/epam/edp-tekton/blob/release/0.11/charts/pipelines-library/values.yaml#L374) (If you installed EDP using GitOps approach and created GitServer with helm):

```yaml
gitServers:
  my-gitlab:
    gitProvider: gitlab
    host: gitlab.com
    webhook:
      url: "http://gitlab.example.com"
      skipWebhookSSLVerification: false
    eventListener:
      enabled: true
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      nodeSelector: {}
      tolerations: []
      affinity: {}
```
This configuration allows the codebase operator to use the specified URL to create webhooks in GitLab without relying on the Ingress value. It's important to note that while ingress is required to receive events from GitHub/GitLab, this workaround allows you to proceed if your current focus is exploratory.

Alternatively, you can update your GitServer configuration as follows:
```yaml
kind: GitServer
metadata:
  name: my-gitlab
spec:
  gitHost: gitlab.com
  gitProvider: gitlab
  gitUser: git
  httpsPort: 443
  nameSshKeySecret: "ci-gitlab"
  sshPort: 22
  skipWebhookSSLVerification: false
  webhookUrl: "http://gitlab.example.com"
```
Adopting either of these approaches should resolve the issue with the ingress for the GitServer and ensure the component's status is correctly reflected.

Please don't hesitate to reach out if you have any further questions or require additional assistance.

Best regards,
Sergiy

**Comment by hugoarroyo** [comment]
Thanks @SergK  for your prompt response. 

I have another question, Can I install EDP using istio instead of ngix ingress?

Regards
Hugo

**Comment by SergK** [comment]
Yes, it is indeed possible to utilize the EPAM Delivery Platform (EDP) without the default NGINX Ingress or even the Istio Ingress controller. During the installation process, you have the flexibility to disable the ingress setup for all EDP components. This approach allows you to use alternative methods for traffic routing according to your specific infrastructure requirements. Here's how you can disable ingress for key components:

EDP Portal: You can disable the ingress for the EDP Portal by modifying the values.yaml file available in the GitHub repository. Set the ingress.enabled parameter to false. Access the configuration here: [EDP Headlamp values.yaml](https://github.com/epam/edp-headlamp/blob/master/deploy-templates/values.yaml#L97).

Tekton Part: Similarly, for the Tekton component, adjust the values.yaml file to disable ingress by setting ingress.enabled to false. The relevant configuration can be found here: [EDP Tekton values.yaml](https://github.com/epam/edp-tekton/blob/master/charts/pipelines-library/values.yaml#L317).

Once you have disabled the ingress installation for these components, it is crucial to configure the webhookUrl in the GitServer specification. This URL should direct traffic to the solution you've chosen for handling your ingress needs:

```yaml
kind: GitServer
metadata:
  name: my-gitlab
spec:
  gitHost: gitlab.com
  gitProvider: gitlab
  gitUser: git
  httpsPort: 443
  nameSshKeySecret: "ci-gitlab"
  sshPort: 22
  skipWebhookSSLVerification: false
  webhookUrl: "http://gitlab.example.com" <<<<<<<<<<<<<<<<<< DEFINE THIS VALUE, it's going to be used as webhook URL in you git server
```
On the Istio side, managing traffic flow can be straightforwardly achieved by defining VirtualService and Gateway configurations. These resources enable you to route incoming traffic to the desired endpoints, such as the Tekton Dashboard, EDP Portal, and Event Listener, based on your requirements.

We do the same approach when configuring EDP with https://kubernetes.io/docs/concepts/services-networking/gateway/

**Comment by SergK** [comment]
Meanwhile, I'll try to share configs (values.yaml) next week for the cases you've mentioned, including the Ingress"less" installation.

**Comment by SergK** [comment]
@hugoarroyo, please consult https://github.com/epam/edp-install/blob/master/deploy-templates/values-no-ingress.yaml. The idea is to adjust routing stuff to the Istio objects that are responsible for traffic routing in your case.

**Comment by hugoarroyo** [comment]
@SergK  thank you kindly for the information, I will keep reviewing the documentation, also I wanted to check if EPAM in the near future can support github packages as a container registry

**Comment by SergK** [comment]
@hugoarroyo we do have support for packages https://epam.github.io/edp-install/operator-guide/package-registry/ but let me check with the team, I think we can add out-of-the-box support for the **GitHub container registry**

**Comment by SergK** [comment]
@hugoarroyo here is what you can do. Create Container Registry 'DockerHub'

<img width="1316" alt="image" src="https://github.com/epam/edp-install/assets/1520525/9709fd04-c44b-42ab-8988-e334971fc47d">

Then edit **kaniko-docker-config** and **regred** in your epd namespace, and align them to format:
```yaml
          {
            "auths": {
              "ghcr.io": {
                "auth": "$(echo -n "$GIT_USERNAME:$GIT_PASSWORD" | base64 -w0)"
              }
            }
          }
```

And this should work

**Comment by hugoarroyo** [comment]
Hi @SergK 

I tried what you recommend, but after doing that I can only see

`"60b58e48-2ea0-4a6c-ac9b-2de7b73ef290","url":"**https://ghcr.io/v2/**"} {"level":"info","ts":"2024-04-09T00:42:49Z","msg":"Connection failed","controller":"secret","controllerGroup":"","controllerKind":"Secret","Secret":{"name":"regcred","namespace":"edp"},"namespace":"edp","name":"regcred","reconcileID":"60b58e48-2ea0-4a6c-ac9b-2de7b73ef290","error":"**http status code 401 Unauthorized**"}`

I know that my configuration works because I'm using the same user and token for pulling and pushing containers to github packages, this is my config file

`
{
    "auths": {
       "https://ghcr.io": {
          "auth": "this is my base64 user passowrd"
       }
    }
}
` 
But I can't pass the 401 unauthorized response 

Thanks

**Comment by SergK** [comment]
ok, I've found a working configuration:
1. Ensure you are using dockerhub as registry
2. Then update `kaniko-docker-config` and `regcred` registry endpoint to `{"auths":{"https://ghcr.io":` 
3. It is ok to have 401 issue for now (we will fix it in the next release)
4. Update edp-configmap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: edp-config
  namespace: edp
data:
  container_registry_host: ghcr.io
  ....
```
6. Run build pipeline and see success build in logs:

To summarize, you should follow github approach and just update values in two places:
https://ghcr.io for docker cred and config map **container_registry_host**
