### ISSUE TITLE
`kaniko-docker-config` has two secretKey fields

### ISSUE THREAD

**Issue by Artem-Zahumonnyi** [epam/edp-install#63]
**Describe the bug**
`kaniko-docker-config` has two secretKey fields.
https://github.com/epam/edp-install/blob/cf0f571f596b48c2be1423b1871f1f51b118e23b/deploy-templates/templates/external-secrets/externalsecret-kaniko.yaml#L22C5-L22C14

**To Reproduce**

```bash
helm pull epamedp/edp-install --version 3.4.1 --untar
helm template edp-install . --output-dir somedir -n shared
```

#### What did you expect to see?

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kaniko-docker-config
spec:
  target:
    template:
      metadata:
        labels:
          app.edp.epam.com/secret-type: registry
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .secretValue }}"
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: secretValue
    remoteRef:
      key: /edp/deploy-secrets
      property: kaniko-docker-config
```

#### What did you see instead?

```yaml
---
# Source: edp-install/templates/external-secrets/externalsecret-kaniko.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kaniko-docker-config
spec:
  target:
    template:
      metadata:
        labels:
          app.edp.epam.com/secret-type: registry
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .secretValue }}"
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: /edp/deploy-secrets
      property: kaniko-docker-config
    secretKey: secretValue
```
