### ISSUE TITLE
Migrate keycloak users under sso subsection

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#83]
Acceptance Criteria:

- there are no available manage users under global subsection;
- values.yaml should looks like:
```
# -- Enable SSO for EDP components. Required keycloak-operator deployment. Default: false
sso:
  enabled: true
  # -- Keycloak URL
  keycloakUrl: https://keycloak.example.com
  # -- Administrators of your tenant
  admins:
    - "stub_user_one@example.com"
  # -- Developers of your tenant
  developers:
    - "stub_user_one@example.com"
    - "stub_user_two@example.com"
```
